# Generated by Django 3.2.8 on 2022-01-05 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippinginfo',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
