# Generated by Django 3.2.8 on 2022-01-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_shippinginfo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippinginfo',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Customer name'),
        ),
    ]
